# Generated by Django 5.2.7 on 2025-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=200)),
                ('description', models.TextField(help_text='Event description')),
                ('timing', models.CharField(help_text='Event timing (e.g., 2:00 PM - 5:00 PM)', max_length=100)),
                ('location', models.CharField(help_text='Event location', max_length=200)),
                ('additional_info', models.TextField(blank=True, help_text='Additional information about the event (e.g., number of spots)', null=True)),
                ('date', models.DateField(help_text='Event date')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', help_text='Event status - automatically determines if shown in upcoming or past events', max_length=10)),
                ('image', models.ImageField(help_text='Event image', upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
    ]
