# Generated by Django 5.2.7 on 2025-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title', max_length=200)),
                ('image', models.ImageField(help_text='Upload photo', upload_to='gallery/')),
                ('section', models.CharField(choices=[('workshops', 'Workshops'), ('events', 'Events'), ('projects', 'Projects'), ('social', 'Social')], help_text='Select the section where this photo should appear', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
