# Generated by Django 5.2.7 on 2025-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='section',
            field=models.CharField(choices=[('workshops', 'Workshops'), ('events', 'Events'), ('projects', 'Projects'), ('social', 'Social'), ('other', 'Other')], help_text='Select the section where this photo should appear', max_length=20),
        ),
    ]
