# Generated by Django 5.2.7 on 2025-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the club', max_length=200)),
                ('description', models.TextField(help_text='Club description')),
                ('registration_status', models.CharField(choices=[('open', 'Registration Open'), ('closed', 'Registration Closed')], default='closed', help_text='Current registration status', max_length=10)),
                ('spots', models.IntegerField(default=0, help_text='Number of available spots')),
                ('image', models.ImageField(help_text='Club image', upload_to='clubs/')),
                ('google_form_link', models.URLField(blank=True, help_text='Google Form link for registration (Apply Now button will only appear if this is filled)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['-created_at'],
            },
        ),
    ]
